max_parallel_tasks: 5
max_retries: 3
retry_delay: 5

region: "china"
build_dir: "build"

upload:
  auto_push: true
  registry_type: "dockerhub"
  username: "your-username"
  password: "your-password"

build:
  # Vanilla
  - tag: "bluefunny/minecraft:vanilla-j8"
    build_type: "vanilla"
    build_args:
      JAVA: "8"
  - tag: "bluefunny/minecraft:vanilla-j11"
    build_type: "vanilla"
    build_args:
      JAVA: "11"
  - tag: "bluefunny/minecraft:vanilla-j17"
    build_type: "vanilla"
    build_args:
      JAVA: "17"
  - tag: "bluefunny/minecraft:vanilla-j21"
    build_type: "vanilla"
    build_args:
      JAVA: "21"
  # MCDReforged
  - tag: "bluefunny/minecraft:mcdr-j8"
    build_type: "mcdr"
    build_args:
      JAVA: "8"
  - tag: "bluefunny/minecraft:mcdr-j11"
    build_type: "mcdr"
    build_args:
      JAVA: "11"
  - tag: "bluefunny/minecraft:mcdr-j17"
    build_type: "mcdr"
    build_args:
      JAVA: "17"
  - tag: "bluefunny/minecraft:mcdr-j21"
    build_type: "mcdr"
    build_args:
      JAVA: "21"